Add MMCM blinky demo for KC705 target
Add `define BROKEN in blinky.v to generate multiple clocks from MMCM,
which will fail due to missing entries in database.

fasm2frames error:
prjxray.fasm_assembler.FasmLookupError: Segment DB HCLK_CMT_L, key HCLK_CMT_L.HCLK_CMT_MUX_PHSR_PERFCLK3.HCLK_CMT_MUX_MMCM_MUXED2 not found from line 'HCLK_CMT_L_X228Y78.HCLK_CMT_MUX_PHSR_PERFCLK3.HCLK_CMT_MUX_MMCM_MUXED2'
Segment DB CMT_TOP_L_LOWER_B, key CMT_TOP_L_LOWER_B.CMT_L_LOWER_B_CLK_PERF2.CMT_LR_LOWER_B_MMCM_CLKOUT1 not found from line 'CMT_TOP_L_LOWER_B_X228Y61.CMT_L_LOWER_B_CLK_PERF2.CMT_LR_LOWER_B_MMCM_CLKOUT1'
Segment DB HCLK_IOI, key HCLK_IOI.HCLK_IOI_RCLK3.HCLK_IOI_IO_PLL_CLK3_DMUX not found from line 'HCLK_IOI_X235Y78.HCLK_IOI_RCLK3.HCLK_IOI_IO_PLL_CLK3_DMUX'
Segment DB HCLK_IOI, key HCLK_IOI.HCLK_IOI_CK_BUFRCLK0.HCLK_IOI_RCLK2RCLK0 not found from line 'HCLK_IOI_X235Y78.HCLK_IOI_CK_BUFRCLK0.HCLK_IOI_RCLK2RCLK0'
Segment DB HCLK_IOI, key HCLK_IOI.HCLK_IOI_RCLK2RCLK0.HCLK_IOI_RCLK_OUT0 not found from line 'HCLK_IOI_X235Y78.HCLK_IOI_RCLK2RCLK0.HCLK_IOI_RCLK_OUT0'
Segment DB HCLK_IOI, key HCLK_IOI.HCLK_IOI_RCLK2.HCLK_IOI_IO_PLL_CLK2_DMUX not found from line 'HCLK_IOI_X235Y78.HCLK_IOI_RCLK2.HCLK_IOI_IO_PLL_CLK2_DMUX'
Segment DB HCLK_CMT_L, key HCLK_CMT_L.HCLK_CMT_MUX_PHSR_PERFCLK2.HCLK_CMT_MUX_MMCM_MUXED3 not found from line 'HCLK_CMT_L_X228Y78.HCLK_CMT_MUX_PHSR_PERFCLK2.HCLK_CMT_MUX_MMCM_MUXED3'
Segment DB HCLK_IOI, key HCLK_IOI.HCLK_IOI_CK_BUFRCLK1.HCLK_IOI_RCLK2RCLK1 not found from line 'HCLK_IOI_X235Y78.HCLK_IOI_CK_BUFRCLK1.HCLK_IOI_RCLK2RCLK1'
Segment DB CMT_TOP_L_LOWER_B, key CMT_TOP_L_LOWER_B.CMT_L_LOWER_B_CLK_PERF3.CMT_LR_LOWER_B_MMCM_CLKOUT2 not found from line 'CMT_TOP_L_LOWER_B_X228Y61.CMT_L_LOWER_B_CLK_PERF3.CMT_LR_LOWER_B_MMCM_CLKOUT2'
Segment DB HCLK_IOI, key HCLK_IOI.HCLK_IOI_RCLK2RCLK1.HCLK_IOI_RCLK_OUT1 not found from line 'HCLK_IOI_X235Y78.HCLK_IOI_RCLK2RCLK1.HCLK_IOI_RCLK_OUT1'